# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8857b8b8321c15ea9ddb93a5931817b8ed2184f5f07cc7a7993683661e1d1988acd4b37a0e25852ff5f0a81995165f31acff4cdcb99bc74b0e3bbce71c395f77

test:
  secret_key_base: 483c6884095fdb725798efc8e5ffea11e2c5c69219d8b96d866bb32197e9db80614fece0ee5fff1522ade44c70920d32ec3c013ef46d3893e60e863a18e82553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
